server:
  port: 8081
  servlet:
    context-path: /supershop


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: spring2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false

files:
  storepath:
    icons:  "C:\\Java\\Spring2\\Lesson3\\DZ\\Icons"
    images: "C:\\Java\\Spring2\\Lesson3\\DZ\\Images"